### ISSUE TITLE
Create a constants file to contain the base API URL

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#101]
**Is your feature request related to a problem? Please describe.**
- Currently, If we need to change the hostname of the API URLs we need to change every file that contains the API URLs and there will be 19+ file changes. 
- This is not a good approach and we have to face issues when committing the changes

**Describe the solution you'd like**
- Create a file called `constants.ts` in the root 
- Add the base URL as a variable ex: `const API_URL = 'http://localhost:8080/api'`
- Replace the existing API URLs with the variable
ex: `http://localhost:8080/api/programs` will be `${API_URL}/programs`

**Comment by gajindubandara** [comment]
Can you assign this to me?

**Comment by anjula-sack** [comment]
sure go ahead! @gajindubandara
