### ISSUE TITLE
Restrict unauthorised users from accessing the authorised UIs

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#103]
**Is your feature request related to a problem? Please describe.**
- Currently, Users can access the authorised UI's without being authorised. If the user trying to access a UI that needs to be authorised the user should be redirected to the sign-in page

**Describe the solution you'd like**
- Check whether the user has logged in or not when the user trying to access the UIs that requires to be authorised.

**Comment by Gravewalker666** [comment]
Working on it
