### ISSUE TITLE
Space in a folder name causes cloning issues

### ISSUE THREAD

**Issue by NethmiRodrigo** [sef-global/scholarx-frontend-v1#120]
**Describe the bug**
The space in the folder name 'src/components /LogInModal' prevents the repository from being cloned properly

**To Reproduce**
1. Clone the repository
2. See error

**Expected behavior**
Successful clone of the repository

**Screenshots**
![image](https://user-images.githubusercontent.com/34070216/116083282-12889180-a6ba-11eb-9975-f666332fdb8b.png)
![image](https://user-images.githubusercontent.com/34070216/116083327-1e745380-a6ba-11eb-8401-fce74e9a9a56.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Additional context**
The space in the path name (probably an error when the subdirectory was created) is creating this issue. Instead of recognizing 'LogInModal' as a subdirectory, it has been added to the folder name of the folder 'components

**Comment by Gravewalker666** [comment]
Thank you very much for pointing out @NethmiRodrigo, I'll look into it
