### ISSUE TITLE
Create a footer for the scholarX 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#126]
**Is your feature request related to a problem? Please describe.**
- Currently, we don't have a footer and it's something we should have.

**Describe the solution you'd like**
- Create a footer component and add them to the relevant views

**Describe alternatives you've considered**
- You can refer to the footer in [AcadeMix](http://apps.sefglobal.org/academix/)

![image](https://user-images.githubusercontent.com/43912578/116339815-bb8ad580-a7fb-11eb-9a3b-2bef30b8b0a3.png)

**Comment by kumuditha-udayanga** [comment]
@anjula-sack  Can I work on this issue?

**Comment by anjula-sack** [comment]
sure go ahead! @kumuditha-udayanga
