### ISSUE TITLE
The footer needs to be mobile responsive 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#137]
**Describe the bug**
- Footer is not mobile responsive.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the homepage
2. Scroll down to the footer
3. Switch to the mobile view
4. See the error

**Expected behavior**
- The footer should be mobile responsive

**Screenshots**
![image](https://user-images.githubusercontent.com/43912578/117997323-7cfb2c00-b360-11eb-869b-919e7880b625.png)

**Comment by kumuditha-udayanga** [comment]
I would like to work on this issue.

**Comment by anjula-sack** [comment]
Awesome!
