### ISSUE TITLE
Update the mentee apply page content

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#157]
**Is your feature request related to a problem? Please describe.**
- We need to update the mentee apply view 

**Describe the solution you'd like**
- Create a google doc add it as the template
- Get the google doc link from the user

![image](https://user-images.githubusercontent.com/43912578/119248219-4e295500-bbad-11eb-992b-de5e046b15b2.png)

**Comment by kumuditha-udayanga** [comment]
@anjula-sack Can you assign me?
