### ISSUE TITLE
Create Apply as a mentor view

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/scholarx-frontend-v1#16]
**Is your feature request related to a problem? Please describe.**
- Need to develop the "apply as a mentor view" on the admin dashboard.

**Describe the solution you'd like**
- Create a dummy UI adhering to the given view on the admin wireframes.

**Additional context**
- This is the view that needs to be developed, a dummy form would suffice.
- For additional details, please follow this link to the [wireframes thread](https://sef.discourse.group/t/designing-wireframes-for-scholarx-platform/148).

![image](https://user-images.githubusercontent.com/60275681/95879584-26128180-0d94-11eb-98fe-b1bfae4b04f4.png)

**Comment by bojanmiles** [comment]
@Gimhan-minion can i take this one?

**Comment by Gimhan-minion** [comment]
@MilePaor Yeah if you can submit it before October 20th it's fine. :+1:

**Comment by Gimhan-minion** [comment]
Hi @MilePaor Actually we've changed the wireframes now. This isn't the requirement at the moment. I couldn't update the issue and sorry for that. I've already created the new one. But you can contribute to more issues on our repository.

(Join the discussion for more information):hugs: 
SEF Hive:- https://sef.discourse.group/
