### ISSUE TITLE
Change the appearance of the checkbox in mentor selection - Phase 6 

### ISSUE THREAD

**Issue by gajindubandara** [sef-global/scholarx-frontend-v1#177]
**Describe the bug**
In Phase 6, When the mentee is selecting a mentor, the checkboxes are not visible enough

**Expected behavior**
Make the checkboxes more visible

**Screenshots**
![Screenshot from 2021-06-07 21-01-23](https://user-images.githubusercontent.com/63200586/121046509-a37f7c00-c7d3-11eb-8603-3e726e57348a.png)

**Comment by kumuditha-udayanga** [comment]
Can i work on this issue?

**Comment by anjula-sack** [comment]
Sure go ahead @kumuditha-udayanga

**Comment by kumuditha-udayanga** [comment]
Please refer to this thread, to check the current status of this issue.

https://sef.discourse.group/t/improve-the-ui-of-mentor-approval-scene/315
