### ISSUE TITLE
Responsive issue in mentor card in apply as a mentee view

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#186]
**Describe the bug**
- In the apply as a mentee view, We are showing the mentors along with their names. But when the name is short it comes to the same line as the avatar. 

**Screenshots**
<img width="1334" alt="Screenshot 2021-06-15 at 4 44 09 PM" src="https://user-images.githubusercontent.com/43912578/122043412-f02d0d80-cdf8-11eb-883a-1f395f1f40d2.png">

**To Reproduce**
1. Go to a program where you can apply
2. See the issue with small names

**Expected behavior**
- Mentor name should be below the avatar regardless of the name length like the below screen shot
![image](https://user-images.githubusercontent.com/43912578/122044040-a8f34c80-cdf9-11eb-8e0f-caa98b0c404d.png)

**Desktop (please complete the following information):**
 - OS: Mac Os Big Sur 11.4
 - Browser: Chrome

**Comment by kumuditha-udayanga** [comment]
I would like to work on this issue

**Comment by anjula-sack** [comment]
> I would like to work on this issue
Awesome go ahead
