### ISSUE TITLE
Move mentee APIs to the mentee-services file in ManageMentees scene

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#191]
**Is your feature request related to a problem? Please describe.**
- According to the current implementation we are using Axios call inside our JSX files. 
- Move the APIs in the ManageMentees scene to a single file.

**Describe the solution you'd like**
- Create the `mentee-services.ts` file 
- Move all the mentee related APIs to the created file

https://sef.discourse.group/t/separating-the-api-calls-from-the-jsx-files/310

https://github1s.com/sef-global/scholarx-frontend/blob/HEAD/src/scenes/Dashboard/scenes/ManageMentees/index.tsx#L58

**Comment by NethmiRodrigo** [comment]
@anjula-sack can I work on this?

**Comment by anjula-sack** [comment]
Sure! go ahead @NethmiRodrigo
