### ISSUE TITLE
Move program APIs to the program-services file in EditProgram scene

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#192]
**Is your feature request related to a problem? Please describe.**
- According to the current implementation we are using Axios call inside our JSX files. Move them to a single file.

**Describe the solution you'd like**
- Move all the program related APIs to the program-services.ts in this file

https://github1s.com/sef-global/scholarx-frontend/blob/HEAD/src/scenes/Dashboard/scenes/EditProgram/index.tsx#L7

**Comment by kumuditha-udayanga** [comment]
@anjula-sack , Can I work on this issue
