### ISSUE TITLE
Change "Ongoing Programs" tab name

### ISSUE THREAD

**Issue by kumuditha-udayanga** [sef-global/scholarx-frontend-v1#197]
**Is your feature request related to a problem? Please describe.**
- It was suggested that we should change the “Ongoing Programs” tab name to a different one, the reason is there is a state called “Ongoing”.

**Describe the solution you'd like**
- Come up with a different name for the tab.

![Screenshot 2021-07-15 at 12 06 21](https://user-images.githubusercontent.com/27630091/125740456-ea54cd83-85c6-4b36-9ce3-9c14f5f9ffc8.png)

**Comment by kumuditha-udayanga** [comment]
Join the discussion using the link below
https://sef.discourse.group/t/come-up-with-a-different-name-for-ongoing-programs-tab/329

**Comment by kumuditha-udayanga** [comment]
@anjula-sack, Can you assign me for this

**Comment by anjula-sack** [comment]
Sure! go ahead
