### ISSUE TITLE
Prevent showing 'Manage' button to the mentor in "MENTEE_APPLICATION" state

### ISSUE THREAD

**Issue by kumuditha-udayanga** [sef-global/scholarx-frontend-v1#204]
**Describe the bug**
- MENTEE_APPLICATION period showing a manage button for mentors (in my programs) 

**To Reproduce**
- Add a condition to prevent showing the button.

**Expected behaviour**
- 'Manage' button shouldn't appear to mentors in the "MENTEE_APPLICATION" state.

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Browser : Safari
 - Version : 14.0.1

**Comment by kumuditha-udayanga** [comment]
@anjula-sack, can you assign me for this issue

**Comment by anjula-sack** [comment]
Go ahead
