### ISSUE TITLE
As a mentee I should be able to view my mentor even in the ongoing state

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#223]
**Is your feature request related to a problem? Please describe.**
- It's better to show the mentor of a mentee even after the `MENTOR_CONFIRMATION` period.

**Describe the solution you'd like**
- My mentor view needs to be accessible even after the  `MENTOR_CONFIRMATION` period

**Comment by kumuditha-udayanga** [comment]
@anjula-sack, Can i work on this issue.
