### ISSUE TITLE
Update the mentee application UI 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#254]
**Is your feature request related to a problem? Please describe.**
- The current mentee application flow is now changed. So we need to update the mentee application UI according to that.

**Describe the solution you'd like**
- Update the mentee application UI
- Wireframes can be found using [this link](https://app.diagrams.net/#G1870vcUE9U2_D7dDnUMqav_Og8bkb21kv)
![image](https://user-images.githubusercontent.com/43912578/142362438-e59f0591-5149-40f9-b2c5-5dce03942b5a.png)

**Additional context**
- Follow the [hive thread ](https://sef.discourse.group/t/scholarx-february-edition)to get more details.

**Comment by cmdrGuyson** [comment]
I will work on this issue :)
