### ISSUE TITLE
Add the mentor search in the manage mentees view

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#257]
**Is your feature request related to a problem? Please describe.**
- As the admin, I should be able to search for a mentor and see how many mentees have been assigned to that mentor.

**Describe the solution you'd like**
- Implement the mentor search component
- Use dummy data instead of the API implementation 

**Additional context**
![image](https://user-images.githubusercontent.com/43912578/144211569-3c0c02bc-d015-46b9-b5e4-e64d026be8af.png)
![image](https://user-images.githubusercontent.com/43912578/144211541-69e7677d-ea34-4330-8966-4287bbb6e1c1.png)

**Comment by kumuditha-udayanga** [comment]
@anjula-sack, I would like to work on this issue.

**Comment by anjula-sack** [comment]
> @anjula-sack, I would like to work on this issue.

go ahead
