### ISSUE TITLE
Integrate change assignee and change state API

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#258]
**Is your feature request related to a problem? Please describe.**
- As an admin, I should be able to change the current assignee and the state of a mentee.

**Describe the solution you'd like**
- Integrate the relevant APIs to the correct dropdowns in the manage mentee table.
![image](https://user-images.githubusercontent.com/43912578/144213340-e7227b18-735a-41c9-8f5b-bdf7e19b63eb.png)

**Additional context**
 - Here's the [API doc ](https://docs.google.com/document/d/1SFxgduCtF8rz7Mc6SKAA91hF4C6gQIITM9FkobyFWIU/edit?usp=sharing)
 - You can find the relevant payloads in the API Doc

**Comment by Piumal1999** [comment]
Duplicate issue. Fixed with #280
