### ISSUE TITLE
Show the selected mentees of a mentor after the selection

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#266]
**Is your feature request related to a problem? Please describe.**
- We need to show the selected mentees to the mentor. We already have this view but only needs to update the API

**Describe the solution you'd like**
- Update the API
- Update the relevant UI

**Additional context**
- The API can be found [here](https://docs.google.com/document/d/1SFxgduCtF8rz7Mc6SKAA91hF4C6gQIITM9FkobyFWIU/edit?usp=sharing)

**Comment by kumuditha-udayanga** [comment]
@anjula-sack, I would like to work on this issue.

**Comment by Gravewalker666** [comment]
This is not relevant at this point, closing the issue
