### ISSUE TITLE
Update Admin Change State UI

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx-frontend-v1#267]
**Is your feature request related to a problem? Please describe.**
We need to add the new program states of scholarx-february edition to the admin dashboard 

**Describe the solution you'd like**
Update the Admin Dashboard by using the following program states order:
1. CREATED
2. MENTOR_APPLICATION
3. MENTOR_SELECTION
4. MENTEE_APPLICATION
5. ADMIN_MENTEE_FILTRATION - "During this state, the admin can review the mentee applications and assign them to mentors for further review."
6. MENTEE_SELECTION
7. WILDCARD - "During this state, the admin can assign mentors for the mentees who are not approved by mentors."
8. ONGOING
9. COMPLETED
10. REMOVED

**Additional context**
The Endpoint is the same endpoint we had in previous edition

**Comment by 99sumedha** [comment]
Hello @Piumal1999, Can you assign me this issue :)

**Comment by Piumal1999** [comment]
@99sumedha I added the missing state descriptions.

> CREATED
MENTOR_APPLICATION
MENTOR_SELECTION
MENTEE_APPLICATION
ADMIN_MENTEE_FILTRATION - "During this state, the admin can review the mentee applications and assign them to mentors for further review."
MENTEE_SELECTION
WILDCARD - "During this state, the admin can assign mentors for the mentees who are not approved by mentors."
ONGOING
COMPLETED
REMOVED

**Comment by Piumal1999** [comment]
Also update the `src/scenes/Home/components/MentorPrograms/components/MentorProgramCard/interfaces.ts` file

**Comment by 99sumedha** [comment]
@Piumal1999 can you also send me the names of the new states.

**Comment by Piumal1999** [comment]
ADMIN_MENTEE_FILTRATION - "Admin-Mentee filtration period"
WILDCARD - "Wildcard period"
