### ISSUE TITLE
Admins should be able to view the mentor application

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx-frontend-v1#274]
**Is your feature request related to a problem? Please describe.**
"View Application" option of Mange Mentor UI(Admin Dashboard) is not working after the backend changes

**Describe the solution you'd like**
Admins should be able to view the mentor's application by clicking the "View Application" button

**Describe alternatives you've considered**
N/A

**Additional context**
Previously we used an endpoint to get the mentor responses, and showed them on the drawer. But now, all the mentor details are in the Mentor Object itself.

**Comment by kumuditha-udayanga** [comment]
@Piumal1999 I would like to work on this issue.

**Comment by Piumal1999** [comment]
Assigned @kumuditha-udayanga
