### ISSUE TITLE
Improve the mentor application UI

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx-frontend-v1#286]
**Is your feature request related to a problem? Please describe.**
We need to update the design of the Mentor Application form. 

**Describe the solution you'd like**
Use the design on Mentee application form

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kumuditha-udayanga** [comment]
@Piumal1999 Can you assign me?

**Comment by Piumal1999** [comment]
Assigned @kumuditha-udayanga
