### ISSUE TITLE
Can't change the state of the program after phase 3

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#29]
**Describe the bug**
- There's a bug with changing the state of a program

**To Reproduce**
1. Go to manage
2. Click on change state 3 times
3. See error

**Expected behavior**
- The admin needs to able to change the state of the program without an issue

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Browser chrome

**Comment by jayasanka-sack** [comment]
@anjula-sack Could you please explain the bug? Also, add some logs, screenshots if you can. (change the issue title with the bug)
