### ISSUE TITLE
Loading animation is still shown even after throwing the error

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#300]
**Describe the bug**
- Sometimes the loading animation is shown even after the throwing error in some API calls.

**To Reproduce**
1. Go to Mentor view
2. Try creating error when applying or editing mentor application
3. See error

**Expected behavior**
- The loading animation shouldn't be shown after showing the error

**Screenshots**
![image](https://user-images.githubusercontent.com/43912578/149649188-b9ba6a87-de83-4a81-8a5c-7e8658174f9c.png)

**Desktop (please complete the following information):**
 - OS: MacOS monteray
 - Browser: Chrome

**Comment by pasindur99** [comment]
May I work on this?

**Comment by jayasanka-sack** [comment]
Please go ahead. :)
