### ISSUE TITLE
Prevent users from accessing pages in wrong states

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx-frontend-v1#301]
**Describe the bug**
Mentor application pages should be only accessible to users/mentors during MENTOR APPLICATION period
Mentee application pages should be only accessible to users/mentees during MENTEE APPLICATION period

**To Reproduce**
1. Go to a page using the URL of that page, in any state
2. See error

**Expected behavior**
Mentor application pages should be only accessible to users/mentors during MENTOR APPLICATION period
Mentee application pages should be only accessible to users/mentees during MENTEE APPLICATION period
If someone accesses those pages during an inaccessible state, redirect to the homepage

**Screenshots**
N/A

**Additional context**
Check the other pages as well

**Comment by kumuditha-udayanga** [comment]
@Piumal1999 I would like to work on this
