### ISSUE TITLE
Bio texts in mentor applications are not properly formatted

### ISSUE THREAD

**Issue by jayasanka-sack** [sef-global/scholarx-frontend-v1#308]
**Describe the bug**
The bio texts in mentor applications are not properly formatted.  

![image](https://user-images.githubusercontent.com/33048395/152640439-8b1f5724-f0fa-49f0-81ac-bccb87131ae3.png)

**To Reproduce**
1. Apply as a mentor
2. Add following to the bio:
```
Lorem Ipsum
Dolalr sit amet: 011223 434535

• Community Development and Capacity Building 
• Social Mobilization 
• Project Management 
• Site-Based Emergency Responses 
• Training Programs 
• Project Evaluation 
• Report Writing 
• Excellent Computer, Multimedia and Social Media Skills 
• Strong Communication and Analytical Skills 
• Design Campaigns 
• Artist – drama, paintings • Author
```
3. Login to the admin dashboard
4. View the application

**Expected behaviour**
The text should be properly formatted. Please follow this StackOverflow question:
https://stackoverflow.com/questions/11599859/forcing-a-long-line-of-text-without-spaces-to-line-break-according-to-parent-c 

```

``` 

![image](https://user-images.githubusercontent.com/33048395/152640480-553a23fe-f464-445a-ab7c-74f3937cba19.png)

**Comment by kumuditha-udayanga** [comment]
@jayasanka-sack I would like to work on this.

**Comment by Piumal1999** [comment]
Assigned @kumuditha-udayanga
