### ISSUE TITLE
Add character limits to mentor/mentee applications

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx-frontend-v1#312]
**Is your feature request related to a problem? Please describe.**
In the mentee/mentor applications, we haven't validated the character count from the frontend. We need to prevent users from entering text exceeding the maximum character limit

**Describe the solution you'd like**
Every field in the mentee/mentor application should have a character limit. (Ex: for expertise, the character limit is 255)
Check the backend or the DB to find the character limits

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kumuditha-udayanga** [comment]
@Piumal1999 I would like to work on this issue

**Comment by miniskynet** [comment]
@anjula-sack please assign this to me

**Comment by miniskynet** [comment]
Hey @Piumal1999 what should be done for fields that have no limit set in the DB? Should I only put restrictions for fields that have a specific character limit?

**Comment by Piumal1999** [comment]
> Should I only put restrictions for fields that have a specific character limit?

Yeah @miniskynet 

These are the limits:

**Mentor application:**
expertise (255)
institution (255)
position (255)

**Mentee application:**
course (255)
university (255)
year (255)

**Comment by miniskynet** [comment]
Thank you @Piumal1999. So should it be like a popup telling the user that there is a limit or should I just put a maxlength attribute which prevents the user from typing further?

**Comment by Piumal1999** [comment]
Something like this would be nice. https://ant.design/components/input/

<img width="598" alt="image" src="https://user-images.githubusercontent.com/27498587/173791116-e09057c3-fd4f-43d0-821e-c718138d5880.png">

**Comment by miniskynet** [comment]
@Piumal1999  is this good? 

![image](https://user-images.githubusercontent.com/49517852/173795596-a931b724-2fc4-4fea-9445-7aea4e3a32ef.png)

**Comment by Piumal1999** [comment]
Yeah @miniskynet . Also let's use `Input` component for university, course and year instead of `TextArea` since those are single-line answers.

**Comment by miniskynet** [comment]
like this right @Piumal1999 ?
![image](https://user-images.githubusercontent.com/49517852/173870141-226538a7-ca7e-4500-bb51-3a0d585db70d.png)

I'll do the same for mentor application as well

**Comment by Piumal1999** [comment]
> like this right @Piumal1999 ?

Yeah. This is nice
