### ISSUE TITLE
Update the home page description

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#314]
**Is your feature request related to a problem? Please describe.**
- The description on the home page needs to be updated.
<img width="811" alt="image" src="https://user-images.githubusercontent.com/43912578/154805210-570a3f9a-20d1-4866-8acf-2cd7f403144b.png">

**Describe the solution you'd like**
- Replace the description with this, 

ScholarX is an exclusive program aimed at providing mentoring support for talented undergraduate students in Sri Lanka. Our mentors are engaged with some of the world’s top universities and Fortune 500 companies and are carefully selected for their expertise in academia and industry.

This free premium mentoring platform was created for Sri Lankans who see the opportunity and positive change brought about by a culture of knowledge and expertise sharing without the limitations of geographical borders.

**Comment by Aman-Mandal** [comment]
Hey can I work on this ? Thankyouu :)

**Comment by anjula-sack** [comment]
> Hey can I work on this ? Thankyouu :)

yeah sure.
