### ISSUE TITLE
Fit the Mentor list in the admin dashboard to view height by paginating 

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/scholarx-frontend-v1#325]
**Describe the bug**
The mentor list overflows over the view height and the current pagination on the list doesn't work properly (Only loads a single page)

**To Reproduce**
1. Go to admin dashboard (manage project after signing in as an admin)
2. Click on manage mentees
3. See error

**Expected behavior**
It should be paginated properly to fit in the view height 

**Screenshots**
Scrolled down view of the mentor list (This should not be scrollable like this until the mentee list is out of the view)
![image](https://user-images.githubusercontent.com/45477334/162608353-85b3f9ef-761c-4177-8af2-c7da25e1d103.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 
 - Browser: Safari
 
**Additional context**
Keep an eye out on the search bar, make sure it works properly even after paginating the list

**Comment by pasindur99** [comment]
May I work on this?
