### ISSUE TITLE
Remove the mentee fetch error notification from admin manage mentors 

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/scholarx-frontend-v1#326]
**Describe the bug**
The admins manage mentees page throws a bunch of couldn't fetch mentees errors for rejected mentors 

**To Reproduce**
1. Go to admin dashboard (manage project after signing in as an admin)
2. Click on manage mentors
3. See error

**Expected behavior**
There should not be a notification at all for fetch manage mentees, on error function of the network call just log the error out and remove the notification pop up

**Comment by gajindubandara** [comment]
I would like to work on this
