### ISSUE TITLE
Update the admin manage mentees table 

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/scholarx-frontend-v1#333]
**Overview**
The admin manage mentees table needs two amendments be done 
- The primary mentor column filter dropdown list should be sorted alphabetically 
- The assigned mentor column cell dropdown should be searchable (Appears searchable now but doesn't work)

**Definition of done**
The users can browse the mentor list on the primary mentor filter dropdown alphabetically and can also search and assign a mentor from the assigned mentor dropdown itself

**Comment by YaiyaSam** [comment]
Im working on this.
