### ISSUE TITLE
Sort the manage mentor page mentor list 

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/scholarx-frontend-v1#339]
**Overview**
The manage mentor list is not sorted 

**Definition of done**
In manage mentor view the list is sorted in the alphabetical order.

**Comment by miniskynet** [comment]
hey @Gravewalker666 please assign this to me

**Comment by miniskynet** [comment]
hey @Gravewalker666 when creating linkedin app, are there any specifications? or is it okay to use random information?

**Comment by Gravewalker666** [comment]
You have to put the correct redirection url. Apart from that nothing specific as I remember

**Comment by miniskynet** [comment]
okay @Gravewalker666 thank you. How soon do you want this completed? I am currently setting everything up, since this is the first time I'm working on the backend stuff.

**Comment by Gravewalker666** [comment]
It's a two week sprint.
Let us know if you need any help setting things up. You can note them down and ask at the mid sprint standup as well (Saturday 7pm standup)

**Comment by miniskynet** [comment]
yeah I'll try to setup things before tomorrows session, and I'll clear up any complications during the standup. Is slack preferable for you? or is this thread better?
