### ISSUE TITLE
Add character limits to edit mentor applications 

### ISSUE THREAD

**Issue by miniskynet** [sef-global/scholarx-frontend-v1#351]
**Is your feature request related to a problem? Please describe.**
The edit mentor application does not have a feature to limit the user from entering beyond the character limit

**Describe the solution you'd like**
Add a character limit to all the fields on the edit mentor application, so that the user does not write anything beyond the database character limit

**Comment by miniskynet** [comment]
@anjula-sack please assign this to me

**Comment by anjula-sack** [comment]
> @anjula-sack please assign this to me

done

**Comment by Piumal1999** [comment]
@miniskynet There's a separate component for `EditMentorApplication` in https://github.com/sef-global/scholarx-frontend/tree/development/src/scenes/Home/scenes/EditMentorApplication.  That's what we had missed.
