### ISSUE TITLE
Sign up page ScholarX logo Issue on Safari

### ISSUE THREAD

**Issue by Gravewalker666** [sef-global/scholarx-frontend-v1#60]
**Describe the bug**
Sign in page scholarX logo is badly stretched on Safari, but works fine on other browsers

**To Reproduce**
1. Go to 'localhost:3000'
2. Click on 'sign up'

**Screenshots**
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/45477334/100836073-a8feb100-3494-11eb-9ead-5d4d483ecd96.png">

**Desktop (please complete the following information):**
 - OS: MacOs 11.0.1
 - Browser: Safari
 - Version: Safari 14.0.1

**Comment by anjula-sack** [comment]
We don't use this page anymore.
