### ISSUE TITLE
Create the edit programme view

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#7]
**Is your feature request related to a problem? Please describe.**
- Need to develop the view to edit an existing program on the admin dashboard.

**Describe the solution you'd like**
- Create a dummy UI adhering to the given view on the admin wireframes.

**Additional context**
- This is the view that needs be developed, a dummy form would suffice.
- For additional details, please follow this link to the [wireframes thread](https://sef.discourse.group/t/designing-wireframes-for-scholarx-platform/148).
![image](https://user-images.githubusercontent.com/43912578/92297337-e74f0780-ef5b-11ea-88c6-681275c4b23d.png)

**Comment by Gravewalker666** [comment]
Resolved via #17
