### ISSUE TITLE
Bugs related to Mentor Application

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/scholarx-frontend-v1#73]
**Is your feature request related to a problem?.**
- After Applying as a mentor, it should redirect to the homepage.
- Rename the button as "Apply as mentor" instead of "Apply as a mentor"

**Describe the solution you'd like**
- Edit the code to complete the above tasks.

**Additional context**
https://docs.google.com/document/d/1YiX0hik7V5DGB7f88HfkVT5Fk455kZ0LjYlJzqR-Z2I/edit?usp=sharing

**Comment by kumuditha-udayanga** [comment]
HI @Gimhan-minion, Can I work on this issue?

**Comment by kumuditha-udayanga** [comment]
I'm working on it.

**Comment by Gimhan-minion** [comment]
Thank you @kumuditha-udayanga. I'll assign you for it :smile_cat:
