### ISSUE TITLE
Create a navbar for scholaraX 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#78]
**Is your feature request related to a problem? Please describe.**
- We need to create a navbar for the scholarX platform

**Describe the solution you'd like**
- Create a layout component
- Create a navbar
   - The navbar contains the logo, scholarX logo and sign in sign out buttons.
 
![scholarx](https://user-images.githubusercontent.com/43912578/107868180-1ae97280-6ea8-11eb-8e9d-70563a2dccdc.png)

**Comment by kumuditha-udayanga** [comment]
@anjula-sack Can you assign me for this issue?

**Comment by anjula-sack** [comment]
sure, Go ahead! @kumuditha-udayanga
