### ISSUE TITLE
Add a new tab to the home page called "Completed Programs"

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#81]
**Is your feature request related to a problem? Please describe.**
- We need to add a new tab just like "All programs" saying "Completed Programs" to show the past completed programs as a Mentor or a Mentee

![image](https://user-images.githubusercontent.com/43912578/107869876-0a8dc380-6eb9-11eb-966d-7d67c52a3395.png)

**Describe the solution you'd like**
- Create the new tab and name it as  "Completed Programs"
- Show the programs that user have participated  as a Mentor or Mentee and the program state is  in "COMPLETED" state 
- In order to see this tab user has to log in 
- Hide the tab if there are no such programs that meet the requirements

**Comment by kumuditha-udayanga** [comment]
@anjula-sack, I would like to work on this issue.

**Comment by anjula-sack** [comment]
Awesome! Go ahead! @kumuditha-udayanga

**Comment by Gravewalker666** [comment]
Don't we already have a tab for this?? @anjula-sack @kumuditha-udayanga

**Comment by Gravewalker666** [comment]
https://github.com/sef-global/scholarx-frontend/blob/13b02f346ac002419137215bffdff74195c2e058/src/scenes/Home/components/PastPrograms/index.tsx#L18-L50

**Comment by anjula-sack** [comment]
Actually past and completed programs are two things.
1. Past programs -> completed programs
2. Completed programs -> program that user was a mentor or a mentee
@Gravewalker666

**Comment by Gravewalker666** [comment]
Oh okay, my bad, I don't see this as an urgent issue that needs to be done right now, but yeah @kumuditha-udayanga go ahead
