### ISSUE TITLE
Prevent the user from applying as a mentor twice

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#82]
**Is your feature request related to a problem? Please describe.**
- Currently, When a program is in "MENTOR_SELECTION" state a user can apply as a mentor twice because we don’t check whether the user has applied or not.
![image](https://user-images.githubusercontent.com/43912578/107873974-5867f300-6edc-11eb-9eab-8deb211b43af.png)

**Describe the solution you'd like**
- Check the user has applied or not
- If the user has applied as a mentor redirect the user to the edit application page

**Comment by kumuditha-udayanga** [comment]
Hi @anjula-sack, can I work on this issue.

**Comment by anjula-sack** [comment]
Sure @kumuditha-udayanga

**Comment by YohanAvishke** [comment]
Hi @kumuditha-udayanga thanks soo much for working on the issue. How is the progress? Any blockers we can help you with?

**Comment by kumuditha-udayanga** [comment]
Hi @YohanAvishke, I've almost finished it. I'll send the PR by evening today. Thank you for checking in.
