### ISSUE TITLE
Add a tag to indicate the program state in homepage when there's no apply buttons

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#88]
**Is your feature request related to a problem? Please describe.**
- Currently, When a program is in "MENTOR_SELECTION" and "MENTEE_SELECTION" the program card doesn't say anything. It's confusing for a new user.

**Describe the solution you'd like**
- Add a tag to indicate the program state in homepage when there's no apply buttons

**Comment by kumuditha-udayanga** [comment]
@anjula-sack, I would like to work on this issue.

**Comment by anjula-sack** [comment]
sure go ahead!
