### ISSUE TITLE
Create manage mentees view 

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#9]
**Is your feature request related to a problem? Please describe.**
- Need to develop the view to manage mentees on the admin dashboard.

**Describe the solution you'd like**
- Create a dummy UI adhering to the given view on the admin wireframes.

**Additional context**
- This is the view that needs to be developed, a dummy form would suffice.
- For additional details, please follow this link to the [wireframes thread](https://sef.discourse.group/t/designing-wireframes-for-scholarx-platform/148).
![image](https://user-images.githubusercontent.com/43912578/92298946-ba0a5580-ef6b-11ea-82f5-16bfa7982824.png)

**Comment by Gravewalker666** [comment]
Resolved via #17
