### ISSUE TITLE
Add two buttons to go to home or edit after submission

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-frontend-v1#90]
**Is your feature request related to a problem? Please describe.**
- Currently, we don't show any results after submitting the application. we need to show a result containing 2 buttons for go to the home and to go to the edit page

**Describe the solution you'd like**
- Add two buttons to go to home or edit after submission

Design - https://ant.design/components/result/

![image](https://user-images.githubusercontent.com/43912578/111902584-3118be80-8a64-11eb-83d4-65174ea4621c.png)

**Comment by kumuditha-udayanga** [comment]
@anjula-sack, Can I work on this issue?

**Comment by anjula-sack** [comment]
Sure go ahead! @kumuditha-udayanga
