### ISSUE TITLE
Migrate to EC2

### ISSUE THREAD

**Issue by YohanAvishke** [sef-global/scholarx-frontend-v1#93]
**Is your feature request related to a problem? Please describe.**
Limitations of Heroku is problematic for a lot of deployments.

**Describe the solution you'd like**
Use a AWS EC2 Ubuntu VPS for the deployments.

**Related Issue**
https://github.com/sef-global/scholarx/issues/117

**Comment by anjula-sack** [comment]
We ended up using heroku and it's already done.
